### ISSUE TITLE
Notebook loading error

### ISSUE THREAD

**Issue by avipars** [biplobsd/ColabNordChecker#3]
![image](https://user-images.githubusercontent.com/5733247/122673356-be40f000-d1d8-11eb-9170-e66a95d9d71b.png)

Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.
Unexpected token P in JSON at position 2881

https://github.com/biplobsd/ColabNordChecker/blob/master/NordChecker.ipynb

**Comment by avipars** [comment]
any tips?

**Comment by biplobsd** [comment]
2624d161de35eb4996b13cfbb95f7ff52abfc4c8 

fixed
